<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-K932JURE" name="Student login" tests="2" failures="2" timestamp="16 Sep 2021 18:23:17 GMT" time="64.88" errors="0">
  <testcase name="userLogin" time="16.047" classname="studentTests.StudentLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Qualicoach] but found [Qualicoach: Log in to the site]">
      <![CDATA[java.lang.AssertionError: expected [Qualicoach] but found [Qualicoach: Log in to the site]
	at studentTests.StudentLoginTest.userLogin(StudentLoginTest.java:31)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- userLogin -->
  <testcase name="userLogin" time="10.366" classname="studentTests.StudentLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Qualicoach] but found [Qualicoach: Log in to the site]">
      <![CDATA[java.lang.AssertionError: expected [Qualicoach] but found [Qualicoach: Log in to the site]
	at studentTests.StudentLoginTest.userLogin(StudentLoginTest.java:31)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- userLogin -->
</testsuite> <!-- Student login -->
